%prefix "exprp"

%value "ast_node_t *"
%auxil "system_t *"

%header {
#include "exprp_utility.h"
}

%source {
#define PCC_ERROR(auxil) system__handle_syntax_error(auxil, SYNTAX_ERROR_UNKNOWN, range__void())
#define PCC_GETCHAR(auxil) system__get_next_char(auxil)
#define PCC_MALLOC(auxil, size) system__allocate_memory(auxil, size)
#define PCC_REALLOC(auxil, ptr, size) system__reallocate_memory(auxil, ptr, size)
#define PCC_FREE(auxil, ptr) system__deallocate_memory(auxil, ptr)
}

main
	<- _ e:expr _ end_of_input
	{
		$$ = e;
	}
	 / _ '"' e:expr '"' _  # adrift be weird
	{
		$$ = e;
	}
	 / _ "'" e:expr "'" _  # because that's just what you probably wouldn't expect
	{
		$$ = e;
	}

expr
	<- l:expr _ ',' _ e:expr_assignment
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_COMMA, range__new($0s, $0e), l, e);
	}
	 / e:expr_assignment
	{
		$$ = e;
	}

expr_assignment
	<- e:expr_or _ '=' _ r:expr_assignment
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_ASSIGN, range__new($0s, $0e), e, r);
	}
	 / e:expr_or
	{
		$$ = e;
	}

expr_or
	<- l:expr_or _ 'OR' _ e:expr_and
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_OR, range__new($0s, $0e), l, e);
	}
	 / e:expr_and
	{
		$$ = e;
	}

expr_and
	<- l:expr_and _ 'AND' _ e:expr_or
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_AND, range__new($0s, $0e), l, e);
	}
	 / e:expr_equality
	{
		$$ = e;
	}

expr_equality
	<- l:expr_equality _ 'EQ' _ e:expr_relation
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_EQ, range__new($0s, $0e), l, e);
	}
	 / l:expr_equality _ 'NE' _ e:expr_relation
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_NE, range__new($0s, $0e), l, e);
	}
	 / e:expr_relation
	{
		$$ = e;
	}

expr_relation
	<- l:expr_relation _ ('LE'/'<=') _ e:expr_addition
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_LE, range__new($0s, $0e), l, e);
	}
	 / l:expr_relation _ ('GE'/'>=') _ e:expr_addition
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_GE, range__new($0s, $0e), l, e);
	}
	 / l:expr_relation _ ('LT'/'<') _ e:expr_addition
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_LT, range__new($0s, $0e), l, e);
	}
	 / l:expr_relation _ ('GT'/'>') _ e:expr_addition
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_GT, range__new($0s, $0e), l, e);
	}
	 / e:expr_addition
	{
		$$ = e;
	}

expr_addition
	<- l:expr_addition _ '+' _ e:expr_multiplication
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_ADD, range__new($0s, $0e), l, e);
	}
	 / l:expr_addition _ '-' _ e:expr_multiplication
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_SUB, range__new($0s, $0e), l, e);
	}
	 / e:expr_multiplication
	{
		$$ = e;
	}

expr_multiplication
	<- l:expr_multiplication _ '*' _ e:expr_pow
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_MUL, range__new($0s, $0e), l, e);
	}
	 / l:expr_multiplication _ '/' _ e:expr_pow
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_DIV, range__new($0s, $0e), l, e);
	}
	 / l:expr_multiplication _ 'mod' _ e:expr_pow
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_MOD, range__new($0s, $0e), l, e);
	}
	 / e:expr_pow
	{
		$$ = e;
	}

expr_pow
	<- e:expr_pow _ '^' _ r:expr_unary
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_OPERATOR_POW, range__new($0s, $0e), e, r);
	}
	 / e:expr_unary
	{
		$$ = e;
	}

expr_unary
	<- '+' _ e:expr_unary
	{
		$$ = system__create_ast_node_unary(auxil, AST_NODE_TYPE_OPERATOR_PLUS, range__new($0s, $0e), e);
	}
	 / '-' _ e:expr_unary
	{
		$$ = system__create_ast_node_unary(auxil, AST_NODE_TYPE_OPERATOR_MINUS, range__new($0s, $0e), e);
	}
	 / 'NOT' _ e:expr_unary  # starlane extension
	{
		$$ = system__create_ast_node_unary(auxil, AST_NODE_TYPE_OPERATOR_NOT, range__new($0s, $0e), e);
	}
	 / e:expr_funccall
	{
		$$ = e;
	}

expr_funccall
	#<- l:expr_funccall '.' c:simplecall '.' e:identifier
	#{
	#	$$ = system__create_ast_node_ternary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), l, c, e);
	#}
	# / '%' e:bracketcall '%'
	<- '%' e:bracketcall '%'
	{
		$$ = e;
	}
	 / e:bracketcall
	{
		$$ = e;
	}
	 / l:expr_funccall '.' e:simplecall
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), l, e);
	}
	 / l:expr_funccall '.' e:identifier
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), l, e);
	}
	 / e:simplecall
	{
		$$ = e;
	}
	 / e:expr_primary
	{
		$$ = e;
	}

simplecall
	<- e:identifier _ '(' _ r:expr _ ')'
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), e, r);
	}

bracketcall
	<- e:identifier '[' _ r:expr _ ']'
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), e, r);
	}
	# some of these functions will take fucking anything, like this:
	# %PCase[%adjectives[%tavernname1%]% %nouns[%tavernname2%]%]%
	# (note the absence of a comma there -- it's just two array-accesses with a space between them)
	# this will need to be evaluated separately and joined back into a single string before getting
	# passed to PCase. That isn't something that can be represented by this grammar, so we need to
	# take another round-trip through the text-splitter in description.cpp
	 / e:identifier '[' r:textcontent ']'
	{
		$$ = system__create_ast_node_binary(auxil, AST_NODE_TYPE_FUNCCALL, range__new($0s, $0e), e, r);
	}

textcontent
	<- t:s e:expr r:textcontent
	{
		$$ = r;
		$$->range = range__new($0s, $0e);
		ast_node__prepend_child($$, e);
		ast_node__prepend_child($$, t);
	}
	 / t:s e:expr
	{
		$$ = system__create_ast_node_variadic(auxil, AST_NODE_TYPE_TEXTCONTENT, range__new($0s, $0e));
		ast_node__prepend_child($$, e);
		ast_node__prepend_child($$, t);
	}
	 / t:s
	{
		$$ = system__create_ast_node_variadic(auxil, AST_NODE_TYPE_TEXTCONTENT, range__new($0s, $0e));
		ast_node__prepend_child($$, t);
	}

s <- !']' (!'%' .)*
	# If anyone goes around doing %PCase[The 100% correct implementation]%, I will slap them with a 100% Slimy Eel.
	{
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_STRING, range__new($0s, $0e));
	}


expr_primary
	<- e:identifier { $$ = e; }
	 / e:integer { $$ = e; }
	 / e:string { $$ = e; }
	 / '(' _ e:expr _ ')' { $$ = e; }
	 / e:errstring { $$ = e; }

identifier
	<- '%' (L/D)(L/D/'-')* '%'
	{
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_VARIABLE, range__new($0s+1, $0e-1));
	}
	 / L(L/D)* !'"'  # (and identifier immediately followed by a quotation mark probably wanted to be a string but is missing its opening quotation mark)
	{
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_IDENTIFIER, range__new($0s, $0e));
	}
	

integer
	<- (!'0' D+ / '0')
	{
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_INTEGER, range__new($0s, $0e));
	}

string
	<- '"' strcontent '"'
	{
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_STRING, range__new($0s+1, $0e-1));
	}

errstring
	<- ('\\"' / (!'"' .))+ '"'  # for error recovery
	{
		system__handle_syntax_error(auxil, SYNTAX_ERROR_MISSING_QUOTEMARK, range__new($0s-1, $0e));
		$$ = system__create_ast_node_terminal(auxil, AST_NODE_TYPE_STRING, range__new($0s, $0e-1));
	}

L <- [a-zA-Z_]
D <- [0-9]
strcontent <- ('\\"' / (!'"' .))*

_ <- space*
space <- [ \t\v\f]
end_of_input <- !.